title: Rohan Sen
description: The online resume (CV) of me (Dim Hoogeveen). I mainly created this to make myself more visible to everyone online.
url: "https://dimhoogeveen.com"
theme: jekyll-theme-minimal

logo: /assets/img/logo_transparent.png
profile_picture: assets/img/DimProfilePicture.jpg
